on:
  push:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      SUBMODULE_PUSH_TOKEN: ${{ secrets.SUBMODULE_PUSH_TOKEN }}
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
    steps:
    - name: Checkout Parent Repository
      uses: actions/checkout@v4
      with:
        submodules: 'true'
        fetch-depth: 0

    - name: Switch draft api to branch
      working-directory: draft_api
      run: |
        git fetch origin "$BRANCH_NAME"
        git switch --detach "origin/$BRANCH_NAME"

    - name: Switch deploy api to branch
      working-directory: deploy_api
      run: |
        git fetch origin "$BRANCH_NAME"
        git switch --detach "origin/$BRANCH_NAME"

    - name: Setup Terraform with specified version on the runner
      uses: hashicorp/setup-terraform@v4
      with:
        terraform_version: 1.9.0

    - name: Terraform format
      id: fmt
      working-directory: test
      run: terraform fmt -check -recursive

    - name: Terraform init
      id: init
      working-directory: test
      run: |
        terraform init \
          -backend-config="bucket=publisher-backend-66885bbaacdaa619638d156d3d" \
          -backend-config="key=cicd/terraform.tfstate" \
          -backend-config="region=eu-west-2"

    - name: Terraform validate
      id: validate
      working-directory: test
      run: terraform validate -no-color

    - name: Terraform Plan
      id: plan
      working-directory: test
      run: terraform plan -no-color

    - name: Terraform Apply
      working-directory: test
      run: terraform apply -auto-approve -no-color

    - name: Terraform Destroy on Failure
      if: failure()
      working-directory: test
      run: terraform destroy -auto-approve -no-color

    - name: Terraform Destroy before Submodule Update
      working-directory: test
      run: terraform destroy -auto-approve -no-color

    - name: Publish draft api
      working-directory: draft_api
      run: |
        git remote set-url origin "https://x-access-token:${SUBMODULE_PUSH_TOKEN}@github.com/SHerlihy/terraform-aws-draft-cors-api.git"
        git push origin HEAD:main

    - name: Publish deploy api
      working-directory: deploy_api
      run: |
        git remote set-url origin "https://x-access-token:${SUBMODULE_PUSH_TOKEN}@github.com/SHerlihy/terraform-aws-deploy-api-public-quota.git"
        git push origin HEAD:main
